# .github/workflows/docs-build.yml

name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Especifica la versión de Python que prefieras

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Delete old folder build
      run: make clean

    - name: Build HTML Documentation
      run: make html

    - name: Upload HTML Documentation
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
        
    - name: Build PDF Documentation
      run: make latexpdf
      
    - name: Upload PDF Documentation
      uses: actions/upload-artifact@v4
      with:
        name: pdf-docs
        path: docs/build/latex/geoexpressvisor.pdf

    # 7. Commit and push the generated documentation
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/build/html docs/*.rst docs/build/latex/*.pdf
        git commit -m "Auto-update documentation"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
